version: '3'
services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: veyron
      MONGO_INITDB_ROOT_PASSWORD: veyronpassword
    restart: always
    networks:
      - veyron-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.b.preprod
    env_file:
      - ./backend/.env.preprod
    ports:
      - "3000:3000"
    volumes:
      - backend_images:/app/public/images
      - backend_uploads:/app/public/uploads
    restart: always
    depends_on:
      - mongodb
    networks:
      - veyron-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.f.preprod
    env_file:
      - ./frontend/.env.preprod
    ports:
      - "8090:80"
    restart: always
    depends_on:
      - backend
    networks:
      - veyron-network

networks:
  veyron-network:

volumes:
  mongodb_data:
  backend_images:
  backend_uploads: