version: '3'

services:
  frontend:
    container_name: veyron-frontend-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.f.production
    image: veyron-frontend-prod
    ports:
      - "127.0.0.1:8091:80"
    env_file:
      - ./frontend/.env.production
    restart: always
    depends_on:
      - backend
    networks:
      - veyron-prod-network

  backend:
    container_name: veyron-backend-prod
    build:
      context: ./backend
      dockerfile: Dockerfile.b.production
    image: veyron-backend-prod
    ports:
      - "127.0.0.1:3001:3000"
    volumes:
      - backend_images_prod:/app/public/images
      - backend_uploads_prod:/app/public/uploads
    env_file:
      - ./backend/.env.production
    restart: always
    depends_on:
      - mongodb
    networks:
      - veyron-prod-network

  mongodb:
    container_name: veyron-mongodb-prod
    image: mongo:latest
    volumes:
      - mongodb_data_prod:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - veyron-prod-network

  plausible_db:
    container_name: veyron-plausible-db
    image: postgres:14-alpine
    restart: always
    volumes:
      - plausible_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - veyron-prod-network

  plausible_events_db:
    container_name: veyron-plausible-events
    image: clickhouse/clickhouse-server:23.3.7.5-alpine
    restart: always
    volumes:
      - plausible_event_data:/var/lib/clickhouse
      - ./plausible/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./plausible/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - veyron-prod-network

  plausible:
    container_name: veyron-plausible
    image: plausible/analytics:v2.0
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - ./plausible/plausible-conf.env
    networks:
      - veyron-prod-network

networks:
  veyron-prod-network:

volumes:
  mongodb_data_prod:
  backend_images_prod:
  backend_uploads_prod:
  plausible_db_data:
  plausible_event_data: