version: '3'

services:
  frontend:
    container_name: veyron-frontend-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.f.production
    image: veyron-frontend-prod
    ports:
      - "127.0.0.1:8091:80"
    env_file:
      - ./frontend/.env.production
    restart: always
    depends_on:
      - backend
    networks:
      - veyron-prod-network

  backend:
    container_name: veyron-backend-prod
    build:
      context: ./backend
      dockerfile: Dockerfile.b.production
    image: veyron-backend-prod
    ports:
      - "127.0.0.1:3001:3000"
    volumes:
      - backend_images_prod:/app/public/images
      - backend_uploads_prod:/app/public/uploads
    env_file:
      - ./backend/.env.production
    restart: always
    depends_on:
      - mongodb
    networks:
      - veyron-prod-network

  mongodb:
    container_name: veyron-mongodb-prod
    image: mongo:latest
    volumes:
      - mongodb_data_prod:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - veyron-prod-network

networks:
  veyron-prod-network:

volumes:
  mongodb_data_prod:
  backend_images_prod:
  backend_uploads_prod: